sudo: false
language: node_js
node_js:
  - node


install:
  - npm ci

addons:
sonarcloud:
  organization: "csc47300-project"
  token:
    secure: "f63f18ff6622aca5ae3ed68a2a159008045aeef5" # encrypted value of your token
  
script:
  - npm run test
  - sonar-scanner

nofications:
  email: false


  
